<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.nervousync</groupId>
        <artifactId>utils-parent</artifactId>
        <version>1.3.0.1</version>
    </parent>
    <artifactId>utils-security</artifactId>
    <packaging>jar</packaging>
    <name>Nervousync Java Security Utilities</name>
    <dependencies>
        <dependency>
            <groupId>org.nervousync</groupId>
            <artifactId>utils-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.nervousync</groupId>
            <artifactId>utils-beans</artifactId>
        </dependency>
        <dependency>
            <groupId>org.nervousync</groupId>
            <artifactId>utils-i18n</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.nervousync</groupId>
            <artifactId>utils-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- Security Support -->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcutil-jdk18on</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk18on</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk18on</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcutil-jdk18on</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>